---
- name: Install udisks2
  become: yes
  pacman:
    name: udisks2
    state: present

- name: Configure auto mount
  become: yes
  template:
    src: 10-udisks.rules.j2
    dest: /etc/udev/rules.d/10-udisks.rules

- name: Verify /media exists
  become: yes
  file:
    path: /media
    state: directory

- name: Configure mount location
  become: yes
  template:
    src: 99-udisks2.rules.j2
    dest: /etc/udev/rules.d/99-udisks2.rules

- name: Install udiskie
  become: yes
  pacman:
    name: udiskie
    state: present
