---
- name: Copy pacman configuration file
  become: yes
  copy:
    src: pacman.conf
    dest: /etc/pacman.conf

- name: Refresh pacman mirrors
  become: yes
  pacman:
    update_cache: yes


- include: shell.yml
- include: packages.yml
- include: journal.yml
