---
- name: Install magic-wormhole
  become: yes
  aur:
    name:
      - python-hkdf
      - python-spake2
      - python-txtorcon
      - magic-wormhole
    user: "{{ user.name }}"
  tags:
    - aur

- name: Jail magic-wormhole
  become: yes
  file:
    src: /usr/bin/firejail
    dest: /usr/local/bin/wormhole
    state: link
  tags:
    - firejail

- name: Push magic-wormhole firejail profile
  become: yes
  copy:
    src: firejail/wormhole.profile
    dest: /usr/local/etc/firejail/wormhole.profile
  notify:
    - activate firejail profiles
  tags:
    - firejail
