---
- name: Install calibre
  become: yes
  pacman:
    name: calibre
    state: present

- name: Jail calibre
  become: yes
  file:
    src: /usr/bin/firejail
    dest: /usr/local/bin/calibre
    state: link
  tags:
    - firejail

- name: Jail ebook-viewer
  become: yes
  file:
    src: /usr/bin/firejail
    dest: /usr/local/bin/ebook-viewer
    state: link
  tags:
    - firejail
