---
- name: Install taskwarrior
  become: yes
  pacman:
    name: task
    state: present

- name: Install timewarrior
  become: yes
  pacman:
    name: timew
    state: present
  notify:
    - refresh holidays

- name: Install taskopen
  become: yes
  aur:
    name: taskopen
    user: "{{ user.name }}"
  tags:
    - aur
