---
- include: tlp.yml

- name: Copy touchpad configuration file
  become: yes
  copy:
    src: 30-touchpad.conf
    dest: /etc/X11/xorg.conf.d/30-touchpad.conf
  tags:
    - libinput

- name: Copy logind configuration file
  become: yes
  copy:
    src: logind.conf
    dest: /etc/systemd/logind.conf

- name: Push low battery warning script
  become: yes
  copy:
    src: lowbatt.sh
    dest: /usr/local/bin/lowbatt mode=0755

- name: Push low battery warning service file
  become: yes
  template:
    src: lowbatt.service.j2
    dest: /etc/systemd/system/lowbatt.service
  notify:
    - reload systemd config

- name: Push low battery timer file
  become: yes
  template:
    src: lowbatt.timer.j2
    dest: /etc/systemd/system/lowbatt.timer
  notify:
    - reload systemd config
    - restart lowbatt

- name: Enable and start lowbatt timer
  become: yes
  service:
    name: lowbatt.timer
    enabled: yes
    state: started

- name: Install light
  become: yes
  pacman:
    name: light
    state: present

- name: Install powertop
  become: yes
  pacman:
    name: powertop
    state: present

- name: Install powerstat
  become: yes
  aur:
    name: powerstat-git
    user: "{{ user.name }}"
  tags:
    - aur

- name: Install cmake for battery-stats
  become: yes
  pacman:
    name: cmake
    state: present

- name: Install battery-stats
  become: yes
  aur:
    name: battery-stats-git
    user: "{{ user.name }}"
  tags:
    - aur

- name: Install battop
  become: yes
  aur:
    name: battop
    user: "{{ user.name }}"
  tags:
    - aur
