---
- name: Install TLP
  become: yes
  pacman:
    name:
      - x86_energy_perf_policy
      - ethtool
      - tlp
      - tlp-rdw
    state: present
  tags:
    - tlp

- name: Copy TLP configuration file
  become: yes
  copy:
    src: tlp.conf
    dest: /etc/default/tlp
  notify:
    - restart tlp
  tags:
    - tlp

- name: Mask systemd radio service
  become: yes
  command: systemctl mask systemd-rfkill.service
  tags:
    - tlp

- name: Mask systemd radio socket
  become: yes
  command: systemctl mask systemd-rfkill.socket
  tags:
    - tlp

- name: Enable TLP
  become: yes
  service:
    name: tlp.service
    enabled: yes
  tags:
    - tlp

- name: Enable TLP sleep
  become: yes
  service:
    name: tlp-sleep.service
    enabled: yes
  tags:
    - tlp
