---
- name: Install zip archive utilities
  become: yes
  pacman:
    name:
      - zip
      - unzip
      - p7zip
    state: present
  tags:
    - zip

- name: Install unrar
  become: yes
  pacman:
    name: unrar
    state: present
  tags:
    - unrar

- name: Install atool
  become: yes
  pacman:
    name: atool
    state: present
  tags:
    - atool

- name: Install par2cmdline
  become: yes
  pacman:
    name: par2cmdline
    state: present
  tags:
    - par2

- name: Install ddrescue
  become: yes
  pacman:
    name: ddrescue
    state: present
  tags:
    - ddrescue
