---
- name: Creating DConf database directory
  become: yes
  file:
    path: /etc/dconf/db
    state: directory
    mode: "0755"
    recurse: yes

- name: Creating DConf profile directory
  become: yes
  file:
    path: /etc/dconf/profile
    state: directory
    mode: "0755"
    recurse: yes