---
- name: Install Unbound
  become: yes
  pacman:
    name: unbound
    state: present

- name: Download root hints
  become: yes
  get_url:
    url: https://www.internic.net/domain/named.cache
    dest: /etc/unbound/root.hints
    force: yes

- name: Copy Unbound configuration file
  become: yes
  template:
    src: unbound.conf.j2
    dest: /etc/unbound/unbound.conf
  notify:
    - restart unbound

- name: Enable and start Unbound
  become: yes
  service:
    name: unbound.service
    enabled: yes
    state: started

- name: Configure resolvconf to use Unbound
  become: yes
  lineinfile:
    dest: /etc/resolvconf.conf
    state: present
    line: "name_servers=127.0.0.1"

- name: Push Unbound root hits update service file
  become: yes
  copy:
    src: roothints.service
    dest: /etc/systemd/system/roothints.service
  notify:
    - reload systemd config

- name: Push Unbound root hits update timer file
  become: yes
  copy:
    src: roothints.timer
    dest: /etc/systemd/system/roothints.timer
  notify:
    - reload systemd config
    - restart roothints
