---
- name: Install GNOME
  become: yes
  pacman:
    name:
      - gnome
      - gnome-extra
      - gnome-tweaks
    state: present

- include: dconf.yml
- include: gtk.yml
- include: gnome_shell.yml
- include: gdm.yml
- include: online_accounts.yml
