---
- name: Add plugdev group
  become: yes
  group:
      name: plugdev
      state: present

- name: Add {{ user.name }} to plugdev group
  become: yes
  user:
      name: "{{ user.name }}"
      groups: plugdev
      append: yes
  tags:
    - user

- name: Install Solaar
  become: yes
  pacman:
      name: solaar
      state: present
