---
- hosts: localhost
  roles:
    - { role: base, tags: ["base"] }
    - { role: gnupg, tags: ["gnupg"] }
    - { role: cron, tags: ["cron"] }
    - {
        role: microcode,
        tags: ["microcode"],
        when: "'AuthenticAMD' in ansible_processor",
      }
    - { role: fish, tags: ["fish"] }
    - { role: hardened, tags: ["hardened"] }
    - { role: ssh, tags: ["ssh"] }
    - { role: ssd, tags: ["ssd"], when: "laptop is defined" }
    - { role: fonts, tags: ["fonts"] }
    - { role: x, tags: ["x"] }
    - { role: gnome, tags: ["gnome"] }
    - { role: iptables, tags: ["iptables"] }
    - { role: nettools, tags: ["nettools"] }
    - { role: networkmanager, tags: ["networkmanager"] }
    - { role: macchiato, tags: ["macchiato"] }
    - { role: ntp, tags: ["ntp"] }
    - { role: firejail, tags: ["firejail"] }
    - { role: tor, tags: ["tor"], when: "tor is defined" }
    - { role: unbound, tags: ["unbound"] }
    - { role: editors, tags: ["editors"] }
    - { role: filesystems, tags: ["filesystems"] }
    - { role: archive, tags: ["archive"] }
    - { role: udisks, tags: ["udisks"] }
    - { role: spell, tags: ["spell"] }
    - { role: browsers, tags: ["browsers"] }
    - { role: media, tags: ["media"] }
    - { role: pianobar, tags: ["pianobar"] }
    - { role: laptop, tags: ["laptop"], when: "laptop is defined" }
    - {
        role: thinkpad,
        tags: ["thinkpad"],
        when: "'ThinkPad' in ansible_product_version",
      }
    - { role: screensaver, tags: ["screensaver"] }
    - { role: taskwarrior, tags: ["taskwarrior"] }
    - { role: cups, tags: ["cups"] }
    - { role: pdf, tags: ["pdf"] }
    - { role: git, tags: ["git"] }
    - { role: virtualbox, tags: ["virtualbox"] }
    - { role: sound, tags: ["sound"] }
    - { role: calibre, tags: ["calibre"] }
    - { role: localtime, tags: ["localtime"], when: "localtime is defined" }
    - { role: wormhole, tags: ["wormhole"] }
    - { role: bluetooth, tags: ["bluetooth"], when: "bluetooth is defined" }
    - { role: hostsctl, tags: ["hostsctl"], when: "hostsctl is defined" }
    - { role: development, tags: ["development"] }
    - { role: logitech, tags: ["logitech"] }
  vars_prompt:
    - name: user_real_name
      prompt: "Please enter your real name"
      private: no

    - name: user_email
      prompt: "Please enter your email"
      private: no
