---
- name: Install hostsctl
  become: yes
  aur:
    name: hostsctl
    user: "{{ user.name }}"
  tags:
    - aur

- name: Push hostsctl config
  become: yes
  template:
    src: hostsctl.conf.j2
    dest: /etc/hostsctl.conf

- name: Update hostsctl
  become: yes
  command: hostsctl update
