---
- name: Install git
  become: yes
  pacman:
    name: git

- name: Setup default git configuraiton
  git_config:
    name: "{{ item.name }}"
    scope: global
    value: "{{ item.value }}"
  with_items:
    - { name: "user.name", value: "{{ user_real_name }}" }
    - { name: "user.email", value: "{{ user_email }}" }
    - { name: "ui.color", value: "True" }
  when: user is defined
