---
- name: Install qemu + virt-manager + ebtables + dnsmasq + libvirt
  become: yes
  pacman:
    name:
      - qemu
      - virt-manager
      - ebtables
      - dnsmasq
      - libvirt
    state: present
  tags:
    - kvm

- name: Start libvirtd service
  become: yes
  systemd:
    name: libvirtd
    state: started
  when: libvirt.enable == True
  tags:
    - kvm

- name: enable libvirtd and ensure it is not masked
  become: yes
  systemd:
    name: libvirtd
    enabled: yes
    masked: no
  when: libvirt.enable == True
  tags:
    - kvm

- name: Add user to libvirt group
  become: yes
  user:
    name: "{{ user.name }}"
    groups: libvirt
    append: yes
  tags:
    - kvm
