---
- include: docker.yml
- include: kvm.yml

- name: Install nodejs + npm + yarn
  become: yes
  pacman:
    name:
      - nodejs
      - yarn
      - npm
    state: present

- name: Create NPM directory
  file:
    name: /home/{{ user.name }}/.npm-global
    state: directory

- name: Set NPM directory
  command: npm config set prefix /home/{{ user.name }}/.npm-global

- name: Write profile file
  copy:
    src: profile.j2
    dest: /home/{{ user.name }}/.profile

- name: Update bashrc
  shell: . /home/{{ user.name }}/.profile

- name: Installation DevTools
  npm:
    name: "{{ item }}"
    state: present
    global: yes
  with_items:
    - generator-jhipster
    - yo
    - "@angular/cli"
    - "@nest/cli"

#
#- name: Install development editor
#  aur:
#    name:
#      - webstorm
#      - intellij-idea-ultimate-edition
#      - goland
#      - visual-studio-code-bin
#    user: "{{ user.name }}"
