---
- name: Install Xorg
  become: yes
  pacman:
    name: xorg-server
    state: present

- name: Install Xinit
  become: yes
  pacman:
    name: xorg-xinit
    state: present

- name: Install xmodmap
  become: yes
  pacman:
    name: xorg-xmodmap
    state: present

- name: Install xdpyinfo
  become: yes
  pacman:
    name: xorg-xdpyinfo
    state: present

- name: Install xev
  become: yes
  pacman:
    name: xorg-xev
    state: present

- name: Install xorg-sessreg
  become: yes
  pacman:
    name: xorg-sessreg
    state: present

- name: Install xautomation
  become: yes
  pacman:
    name: xautomation
    state: present

- name: Install video driver(s)
  become: yes
  pacman:
    name: "{{ video_drivers }}"
    state: present

- name: Add user to video group
  become: yes
  user:
    name: "{{ user.name }}"
    groups: video
    append: yes
  tags:
    - user

- name: Enable middle-click scrolling
  become: yes
  template:
    src: 30-scroll.conf
    dest: /etc/X11/xorg.conf.d/30-scroll.conf
  when: libinput.middle_click_scroll is defined
  tags:
    - libinput

- name: Remap mouse buttons
  become: yes
  template:
    src: 30-button_mapping.conf
    dest: /etc/X11/xorg.conf.d/30-button_mapping.conf
  when: libinput.button_mapping is defined
  tags:
    - libinput

- name: Map keyboard
  become: yes
  template:
    src: 20-keyboard.conf
    dest:  /etc/X11/xorg.conf.d/20-keyboard.conf
  when: libinput.keyboard == True
  tags:
    - libinput

- include: sxhkd.yml
- include: autorandr.yml
- include: srandrd.yml
- include: tilix.yml
- include: autocutsel.yml
