---
- name: Install VirtualBox and dependencies
  become: yes
  pacman:
    name:
      - net-tools
      - virtualbox
      - virtualbox-guest-iso
      - virtualbox-host-dkms
    state: present

- name: Install VirtualBox extensions
  become: yes
  aur:
    name: virtualbox-ext-oracle
    user: "{{ user.name }}"
  tags:
    - aur

- name: Add the user to vboxusers group
  become: yes
  user:
    name: "{{ user.name }}"
    groups: vboxusers
    append: yes
  tags:
    - user
