---
- name: Install chrony
  become: yes
  pacman:
    name: chrony
    state: present

- name: Install chrony networkmanager dispatcher
  become: yes
  aur:
    name: networkmanager-dispatcher-chrony
    user: "{{ user.name }}"
  tags:
    - aur
    - networkmanager

- name: Push chrony configuration file
  become: yes
  copy:
    src: chrony.conf
    dest: /etc/chrony.conf
  notify:
    - restart chrony

- name: Enable and start chrony
  become: yes
  service:
    name: chronyd.service
    enabled: yes
    state: started
